AC_CHECK_FUNCS([fdatasync])
AC_CHECK_FUNCS([mmap])
AC_CHECK_FUNCS([munmap])

AC_CHECK_FUNCS([mkdir])
AC_CHECK_FUNCS([strcasecmp])
AC_CHECK_FUNCS([strerror])
AC_CHECK_FUNCS([strncasecmp])
AC_HEADER_STDBOOL
AC_PROG_RANLIB
