####################################
# Hook to make the ChangeLog
dist-hook:
	@if test -d "$(top_srcdir)/.git" ; \
	then \
		echo Creating ChangeLog && \
		( cd "$(top_srcdir)" && \
		  echo '# Generated by Makefile. Do not edit.'; echo; \
		  ./build-aux/missing --run git log --shortstat ) > $(top_builddir)/ChangeLog.tmp \
		&& mv -f $(top_builddir)/ChangeLog.tmp $(top_distdir)/ChangeLog \
		|| ( rm -f $(top_builddir)/ChangeLog.tmp ; \
		     echo Failed to generate ChangeLog >&2 ); \
	else \
		echo A git clone is required to generate a ChangeLog >&2; \
	fi
